esphome:
    name: homekey-test

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

lock:
  - platform: template
    id: "this_lock"
    name: "Main Lock"
    optimistic: True
    on_lock:
    - logger.log: "Door Locked!"
    on_unlock:
    - logger.log: "Door Unlocked!"

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

external_components:
  source: components

spi:
  clk_pin: 18
  miso_pin: 19
  mosi_pin: 23

pn532_spi:
  id: nfc_spi_module
  cs_pin: 5
  update_interval: 100ms

esp32:
  board: esp32dev
  flash_size: 4MB
  framework:
    type: esp-idf

homekit_base:
  setup_code: '159-35-728'

homekit:
  lock:
    - id: this_lock
      nfc_id: nfc_spi_module
      on_hk_success:
        then:
          if:
            condition:
              lock.is_locked: this_lock
            then:
              lock.unlock: this_lock
            else:
              lock.lock: this_lock
      on_hk_fail:
        lambda: |-
          ESP_LOGI("GSDGSGS", "IT FAILED :(");
      hk_hw_finish: "SILVER"

logger:
  level: DEBUG
