
esphome:
    name: lights_test
    platformio_options:
      board_build.flash_mode: dio

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

output:
  - platform: gpio
    pin: GPIO3
    id: simple_led

external_components:
  source: github://rednblkx/HAP-ESPHome@main
  refresh: 0s

esp32:
  board: esp32-c3-devkitm-1
  flash_size: 4MB
  framework:
    type: esp-idf

homekit_base:
  setup_code: '159-35-728'

homekit:
  light:
    - id: test_light
      meta:
        manufacturer: "AMICI&CO"
        model: "IGNIS"
        serial_number: "42424242"
        fw_rev: "0.16.2"
    - id: desk_light

light:
  - platform: esp32_rmt_led_strip
    id: test_light
    rgb_order: GRB
    pin: GPIO8
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812
    name: "RGB Light"
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: binary
    id: desk_light
    name: "Desk Lamp"
    output: simple_led
    restore_mode: RESTORE_DEFAULT_OFF

logger:
  level: DEBUG
  hardware_uart: USB_SERIAL_JTAG
