
esphome:
    name: custom_components_test
    platformio_options:
      board_build.flash_mode: dio

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  reboot_timeout: 0s

web_server:
  port: 8080

output:
  - platform: gpio
    pin: GPIO3
    id: simple_led

lock:
  - platform: template
    id: "this_lock"
    name: "Main Lock"
    optimistic: True
    on_lock:
    - logger.log: "Door Locked!"
    on_unlock:
    - logger.log: "Door Unlocked!"

sensor:
  - platform: template
    id: "my_sensor"
    name: "Template Sensor"
    unit_of_measurement: "°C"
    icon: "mdi:water-percent"
    device_class: "temperature"
    state_class: "measurement"
    lambda: |-
        return id(number_sensor).state;
    update_interval: 10s
  - platform: template
    id: "my_sensor_second"
    name: "Template Sensor 1"
    unit_of_measurement: "°C"
    icon: "mdi:water-percent"
    device_class: "temperature"
    state_class: "measurement"
    lambda: |-
        return id(number_sensor).state;
    update_interval: 10s

number:
  - platform: template
    name: "Sensor Value"
    min_value: 10
    max_value: 30
    step: 1
    optimistic: True
    id: "number_sensor"

switch:
  - platform: template
    id: some_switch
    name: "Template Switch"
    restore_mode: RESTORE_DEFAULT_OFF
    lambda: |-
      if (id(test_light).current_values.get_state()) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - light.turn_on: test_light
    turn_off_action:
      - light.turn_off: test_light

external_components:
  source: github://rednblkx/HAP-ESPHome@main
  refresh: 0s

spi:
  clk_pin: 4
  miso_pin: 5
  mosi_pin: 6

pn532_spi:
  id: nfc_spi_module
  cs_pin: 7
  update_interval: 100ms

esp32:
  board: esp32-c3-devkitm-1
  flash_size: 4MB
  framework:
    type: esp-idf
    version: 5.2.1
    platform_version: 6.7.0
    sdkconfig_options:
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_LWIP_MAX_SOCKETS: "16"
      CONFIG_LOG_DEFAULT_LEVEL_ERROR: y
      CONFIG_LOG_DEFAULT_LEVEL: "1"
      CONFIG_LOG_MAXIMUM_LEVEL_INFO: y
      CONFIG_LOG_MAXIMUM_LEVEL: "3"
      CONFIG_MBEDTLS_HKDF_C: y

homekit_base:
  meta:
    name: "PRIMO"
    manufacturer: "AMICI&CO"
    model: "IMPERIUM"
    serial_number: "16161616"
    fw_rev: "0.16.2"
  setup_code: '159-35-728'

homekit:
  lock:
    - id: this_lock
      meta:
        manufacturer: "AMICI&CO"
        model: "IMPEDIO"
        serial_number: "42424242"
        fw_rev: "0.16.2"
      nfc_id: nfc_spi_module
      on_hk_success:
        lambda: |-
          ESP_LOGI("HEREHERE", "IssuerID: %s", x.c_str());
          ESP_LOGI("HEREHERE", "EndpointID: %s", y.c_str());
          id(test_light).toggle().perform();
      on_hk_fail:
        lambda: |-
          ESP_LOGI("GSDGSGS", "IT FAILED :(");
      hk_hw_finish: "SILVER"
  light:
    - id: test_light
      meta:
        manufacturer: "AMICI&CO"
        model: "IGNIS"
        serial_number: "42424242"
        fw_rev: "0.16.2"
    - id: desk_light
      meta:
        manufacturer: "AMICI&CO"
        model: "IGNIS"
        serial_number: "42424242"
        fw_rev: "0.16.2"
  sensor:
    - id: my_sensor
      meta:
        manufacturer: "AMICI&CO"
        model: "VARIO"
        serial_number: "42424242"
        fw_rev: "0.16.2"
    - id: my_sensor_second
      meta:
        manufacturer: "AMICI&CO"
        model: "VARIO"
        serial_number: "42424242"
        fw_rev: "0.16.2"
  switch:
    - id: some_switch
      meta:
        manufacturer: "AMICI&CO"
        model: "TRANSMUTO"
        serial_number: "42424242"
        fw_rev: "0.16.2"

button:
  - platform: homekit_base
    factory_reset:
      name: "Reset Homekit pairings"

light:
  - platform: esp32_rmt_led_strip
    id: test_light
    rgb_order: GRB
    pin: GPIO8
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812
    name: "My Light"
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: binary
    id: desk_light
    name: "Desk Lamp"
    output: simple_led
    restore_mode: RESTORE_DEFAULT_OFF

logger:
  # hardware_uart: UART0
  level: DEBUG
